# Directory settings
local_root: "C:\\Github\\ticket_tracker\\ticket_tracker"
output_directory: "prompts"
output_filename: "ticket_tracker_prompt.txt"

# File extensions to include
included_extensions:
  - ".py"
  - ".ipynb"
  - ".html"
  - ".css"
  - ".js"
  - ".jsx"
  - ".md"
  - ".rst"

# Ignore patterns
ignore_patterns:
  directories:
    - ".git"
    - ".github"
    - "__pycache__"
    - "node_modules"
    - "venv"
    - ".venv"
    - "env"
    - ".env"
    - "build"
    - "dist"
    - ".idea"
    - ".vscode"
    - "vendor"
    - "site-packages"
    - "tests"  # Custom ignore
    - "docs"   # Custom ignore
  files:
    - "*.pyc"
    - "*.pyo"
    - "*.pyd"
    - "*.so"
    - "*.dll"
    - "*.dylib"
    - "*.egg-info"
    - "*.egg"
    - "*.whl"
    - ".DS_Store"
    - "Thumbs.db"
    - "*.log"
    - ".env"
    - ".gitignore"
    - "*.lock"
    - "package-lock.json"
    - "*.md"      # Custom ignore
    - "*.test.js" # Custom ignore

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"
