path: /media/user/a16/dev/freepoprompt
ignore_patterns:
  directories:
  - __pycache__
  - .git
  - node_modules
  - venv
  - .venv
  - env
  - .env
  - build
  - dist
  - .pytest_cache
  files:
  - '*.pyc'
  - '*.pyo'
  - '*.pyd'
  - .DS_Store
  - Thumbs.db
  - '*.log'
  - '*.sqlite'
  - '*.db'
max_file_size: 1048576
max_files: 1000
excluded_extensions:
- .jpg
- .jpeg
- .png
- .gif
- .bmp
- .mp3
- .mp4
- .avi
- .mov
- .zip
- .tar
- .gz
- .7z
- .exe
- .dll
- .so
- .dylib
saved_rules:
  global-rules.txt: 'Treat me as an advanced developer you report to.


    Provide detailed technical info on changes.



    # Project Instructions


    Use and update specifications and guidelines as you build the app.


    Write the complete code for every step. Do not get lazy.


    Your goal is to completely finish whatever I ask for.


    ## Project Structure


    ## Rules


    Follow these rules when building the app.


    ### General Rules


    - Avoid code styles that require extra cognitive load;

    - Write maintainable, well-structured code; the next developer to join a project
    should be able to read the code easily

    - Use comments to explain your code;


    #### Env Rules


    - If you update environment variables, update the `.env.example` file


    '
  o1-format.txt: "You will respond with 2 sections: A summary section and an XML section.\n\
    \nHere are some notes on how you should respond in the summary section:\n\nProvide\
    \ a brief overall summary\nProvide a 1-sentence summary for each file changed\
    \ and why.\nProvide a 1-sentence summary for each file deleted and why.\nFormat\
    \ this section as markdown.\nHere are some notes on how you should respond in\
    \ the XML section:\n\nRespond with the XML and nothing else\nInclude all of the\
    \ changed files\nSpecify each file operation with CREATE, UPDATE, or DELETE\n\
    If it is a CREATE or UPDATE include the full file code. Do not get lazy.\nEach\
    \ file should include a brief change summary.\nInclude only the local file path\
    \ starting after the root directory. Do not include the full root path.\nI am\
    \ going to copy/paste that entire XML section into a parser to automatically apply\
    \ the changes you made, so put the XML block inside a markdown codeblock.\nMake\
    \ sure to enclose the code with ![CDATA[CODE HERE]], and don\u2019t put \u201C\
    ===\u201C at the beginning or end of the code.\nHere is how you should structure\
    \ the XML:\n\n<code_changes> <changed_files> <file><file_summary>BRIEF CHANGE\
    \ SUMMARY HERE</file_summary> <file_operation>FILE OPERATION HERE</file_operation>\
    \ <file_path>FILE PATH HERE</file_path> <file_code></file_code></file> REMAINING\
    \ FILES HERE </changed_files> </code_changes>\n\nSo the XML section will be:\n\
    \n__XML HERE__\n"
  o1-pro-base.txt: 'You are an expert software engineer.


    You are tasked with following my instructions.


    Use the included project instructions as a general guide.


    '
