ignore_patterns:
  directories:
  - .git
  - __pycache__
  - node_modules
  - venv
  - .venv
  - env
  - .env
  - build
  - dist
  - .idea
  - .vscode
  - .vs
  - bin
  - obj
  - out
  - target
  - coverage
  - .coverage
  - .pytest_cache
  - .mypy_cache
  - .tox
  - .eggs
  - .sass-cache
  - bower_components
  - jspm_packages
  - .next
  - .nuxt
  - .serverless
  - .terraform
  - vendor
  files:
  - '*.pyc'
  - '*.pyo'
  - '*.pyd'
  - '*.so'
  - '*.dll'
  - '*.dylib'
  - '*.egg'
  - '*.egg-info'
  - '*.whl'
  - .DS_Store
  - .env
  - '*.log'
  - '*.swp'
  - '*.swo'
  - '*.class'
  - '*.jar'
  - '*.war'
  - '*.nar'
  - '*.ear'
  - '*.zip'
  - '*.tar.gz'
  - '*.rar'
  - '*.min.js'
  - '*.min.css'
  - '*.map'
  - .env.local
  - .env.development.local
  - .env.test.local
  - .env.production.local
  - .env.*
  - '*.sqlite'
  - '*.db'
  - '*.db-shm'
  - '*.db-wal'
  - '*.suo'
  - '*.user'
  - '*.userosscache'
  - '*.sln.docstates'
  - thumbs.db
  - '*.cache'
  - '*.bak'
  - '*.tmp'
  - '*.temp'
  - '*.pid'
  - '*.seed'
  - '*.pid.lock'
  - '*.tsbuildinfo'
  - .eslintcache
  - .node_repl_history
  - .yarn-integrity
  - .grunt
  - .lock-wscript
local_root: C:\Github\Repo_Crawler
model: gpt-4
