path: ''  # Default empty path
use_relative_paths: true
model: 'gpt-4'

ignore_patterns:
  directories:
    - __pycache__
    - .git
    - node_modules
    - venv
    - .venv
    - env
    - .env
    - build
    - dist
    - .pytest_cache
    - target
  files:
    - '*.pyc'
    - '*.pyo'
    - '*.pyd'
    - '.DS_Store'
    - 'Thumbs.db'
    - '*.log'
    - '*.sqlite'
    - '*.db'
